# OnlyRoot()
# []
# [CommandProbe("tldr")]
# Installs tldr, a collection of simplified man pages.

- name: "Install tldr"
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - name: "Install tldr (Linux)"
      register: aptout
      apt:
        state: latest
        update_cache: true
        name:
          - tldr
      when: ansible_os_family == "Debian"
    - debug: var=aptout
      when: ansible_os_family == "Debian"

    - name: "Install tldr (macOS)"
      community.general.homebrew:
        name: tldr
      when: ansible_os_family == "Darwin"
