# AnyUserEscalation()
# []
# [CommandProbe("witr")]
# Why is this running?

- name: "Install witr"
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - name: "Install curl (Linux)"
      register: aptout
      apt:
        state: latest
        update_cache: true
        name:
          - curl
      when: ansible_os_family == "Debian"
    - debug: var=aptout
      when: ansible_os_family == "Debian"

    - name: "Install witr"
      register: aptout
      shell:
        cmd: curl -fsSL https://raw.githubusercontent.com/pranshuparmar/witr/main/install.sh | bash
    - debug: var=aptout
