# AnyUserNoEscalation()
# []
# [FileProbe("~/.config/user-dirs.conf")]
# Removes default folders in ~/

- name: "Removes default folders in ~/"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    user_home: "{{ lookup('env', 'HOME') | default(lookup('env', 'USERPROFILE')) }}"
    config_folder: "{{ playbook_dir }}/../../data/config/"
  tasks:
    - name: "Clear existing configuration"
      file:
        path: "{{ user_home }}/.config/user-dirs.conf"
        state: absent

    - name: "Copy configuration"
      copy:
        src: "{{ config_folder }}/user-dirs.conf" 
        dest: "{{ user_home }}/.config/"



